#
#
#   E U R E K A - S E R V E R
#
#
server:
  port: 8020

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


spring:
  application:
    name: eureka-server
  boot:
    admin:
      client:
        url: http://localhost:8021

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
