#
#
#   G A T E W A Y - S E R V E R
#
#
server:
  port: 8010

info:
  app:
    name: "gateway-server"
    description: "Active Pharmacy - Gateway Server"
    version: "1.0.0"

spring:
  application:
    name: gateway-server
  r2dbc:
    url: "r2dbc:mysql://localhost:3306/active_pharmacy_v01"
    username: root
    password: Test12345

#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8020/eureka/

jwt:
  token-expiration-seconds: 1800
  secret-key: "Vr3snA4K8Mfihp4twIHdxc0Vym+v7e7jlBgyZRBjZMM1yjKOvs24++a3AxBLrrCQ9KmXRfhxcl2KlNGmblD+eA=="


#  https://www.javainuse.com/jwtgenerator
#  HS256  javainuse-secret-key