#
#
#   G A T E W A Y - S E R V E R
#
#
server:
  port: 8010

info:
  app:
    name: "gateway-server"
    description: "Active Pharmacy - Gateway Server"
    version: "1.0.0"

spring:
  application:
    name: gateway-server

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8020/eureka/